-- #1
SELECT * FROM CITY
WHERE CountryCode = 'USA'
AND 
Population > 100000;

-- #2
SELECT Name
FROM CITY
WHERE 
Population > 120000
AND
CountryCode = 'USA';

-- #3
SELECT * FROM CITY
WHERE ID = 1661;

-- #4
SELECT NAME FROM CITY
WHERE COUNTRYCODE = 'JPN';

-- #5
SELECT DISTINCT CITY 
FROM STATION
WHERE ID % 2 = 0; 

-- #6
SELECT COUNT(CITY) - COUNT(DISTINCT CITY)
FROM STATION;

-- #7
SELECT CITY FROM STATION 
    WHERE CITY LIKE  'a%'
    OR CITY LIKE  'E%'
    OR CITY LIKE  'I%'
    OR CITY LIKE  'O%'
    OR CITY LIKE  'U%';

-- #8
SELECT DISTINCT CITY FROM STATION 
    WHERE CITY LIKE '%A'
    OR CITY LIKE '%E'
    OR CITY LIKE '%I'
    OR CITY LIKE '%O'
    OR CITY LIKE '%U';

-- #9
SELECT CITY FROM STATION
    WHERE (CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%') 
    AND (CITY LIKE '%A'
        OR CITY LIKE '%E'
        OR CITY LIKE '%I'
        OR CITY LIKE '%O'
        OR CITY LIKE '%U');

-- #10
SELECT DISTINCT CITY 
FROM STATION 
    WHERE CITY NOT LIKE 'A%'
    AND CITY NOT LIKE 'E%'
    AND CITY NOT LIKE 'I%'
    AND CITY NOT LIKE 'O%'
    AND CITY NOT LIKE 'U%';

-- #11
SELECT DISTINCT CITY 
FROM STATION 
    WHERE CITY NOT LIKE '%A'
    AND CITY NOT LIKE '%E'
    AND CITY NOT LIKE '%O'
    AND CITY NOT LIKE '%I'
    AND CITY NOT LIKE '%U';

-- #12
SELECT DISTINCT CITY 
FROM STATION 
WHERE (CITY NOT LIKE 'A%' AND CITY NOT LIKE 'E%' AND CITY NOT LIKE 'I%' AND CITY NOT LIKE 'O%' AND CITY NOT LIKE 'U%') -- not starts with vowels  
OR 
(CITY NOT LIKE '%A' AND CITY NOT LIKE '%E' AND CITY NOT LIKE '%I' AND CITY NOT LIKE '%O' AND CITY NOT LIKE '%U'); -- not ends with vowels




